apiVersion: v1
kind: Service
metadata:
  # THIS NAME MATTERS:
  # Backend calls "jdbc:mysql://mysql:3306"
  name: mysql
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
  # ClusterIP is default, so we can omit 'type: ClusterIP'